name: E2E Test Nixopus API

on:
  push:
    branches:
      - "master"
      - "main"
      - "feat/develop"
    paths:
      - "api/**/*.go"
      - "api/**/*.yaml"
      - "api/**/*.yml"
      - "api/**/*.sql"
  pull_request:
    branches:
      - "master"
      - "main"
      - "feat/develop"
    paths:
      - "api/**/*.go"
      - "api/**/*.yaml"
      - "api/**/*.yml"
      - "api/**/*.sql"
  workflow_dispatch:
    inputs:
      branch:
        description: "Custom branch to run the E2E tests on"
        required: true
        default: "main"

jobs:
  e2e-suite:
    runs-on: ubuntu-latest
    services:
      test-db:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: nixopus
          POSTGRES_PASSWORD: nixopus
          POSTGRES_DB: nixopus_test
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.4"
          check-latest: true
          cache: true
          cache-dependency-path: api/go.sum

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Wait for PostgreSQL
        run: |
          for i in {1..10}; do
            if pg_isready -h localhost -p 5433 -U nixopus -d nixopus_test; then
              echo "PostgreSQL is ready"
              exit 0
            fi
            echo "Waiting for PostgreSQL... $i"
            sleep 2
          done
          echo "PostgreSQL failed to start"
          exit 1

      - name: Wait for Redis
        run: |
          for i in {1..10}; do
            if nc -z localhost 6379; then
              echo "Redis is ready"
              exit 0
            fi
            echo "Waiting for Redis... $i"
            sleep 2
          done
          echo "Redis failed to start"
          exit 1

      - name: Create .env file
        run: |
          cd api
          cat > .env << EOF
          DB_NAME=nixopus_test
          USERNAME=nixopus
          PASSWORD=nixopus
          HOST_NAME=localhost
          DB_PORT=5433
          SSL_MODE=disable
          PORT=8080
          REDIS_URL=redis://localhost:6379
          DOCKER_HOST=unix:///var/run/docker.sock
          JWT_SECRET=test-jwt-secret-key-for-ci
          REFRESH_TOKEN_SECRET=test-refresh-secret-key-for-ci
          ENV=development
          ALLOWED_ORIGIN=http://localhost:3000
          EOF

      - name: Start API server with Go
        env:
          DB_HOST: localhost
          DB_PORT: 5433
          DB_USER: nixopus
          DB_PASSWORD: nixopus
          DB_NAME: nixopus_test
          PORT: 8080
        run: |
          cd api
          echo "Contents of .env file:"
          cat .env
          echo "Starting server with go run..."
          go run main.go > server.log 2>&1 &
          echo $! > server.pid
          echo "Server started with PID: $(cat server.pid)"
          sleep 5
          echo "Server log output:"
          cat server.log || echo "No server.log file found"

      - name: Wait for API server
        run: |
          cd api
          for i in {1..50}; do
            echo "Attempt $i: Testing connection to localhost:8080..."
            
            # Check if server process is still running
            if [ -f server.pid ] && ! kill -0 $(cat server.pid) 2>/dev/null; then
              echo "Server process died, checking logs:"
              cat server.log || echo "No server.log file"
              exit 1
            fi
            
            # Test health endpoint
            if curl -f http://localhost:8080/api/v1/health; then
              echo "Health check passed, testing database connectivity..."
              
              # Test a simple auth endpoint to verify full readiness
              response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/api/v1/auth/is-admin-registered)
              if [ "$response" = "200" ]; then
                echo "API server is fully ready (health + auth endpoints responding)"
                
                # Give additional time for any async initialization
                sleep 3
                exit 0
              else
                echo "Health passed but auth endpoint returned $response, server not fully ready"
              fi
            fi
            
            echo "Waiting for API server... $i"
            sleep 2
            
            # Show server log every 10 attempts
            if [ $((i % 10)) -eq 0 ]; then
              echo "Server log at attempt $i:"
              tail -20 server.log || echo "No server.log file"
            fi
          done
          echo "API server failed to start"
          echo "Final server log:"
          cat server.log || echo "No server.log file"
          exit 1

      - name: Run unit tests + intg tests
        env:
          DB_HOST: localhost
          DB_PORT: 5433
          DB_USER: nixopus
          DB_PASSWORD: nixopus
          DB_NAME: nixopus_test
          TEST_TIMEOUT: 30s
          TEST_RETRY_COUNT: 3
        run: |
          cd api && make test-all

      - name: Stop API server
        if: always()
        run: |
          cd api
          # Kill server process if it exists
          if [ -f server.pid ]; then
            kill $(cat server.pid) || true
            rm server.pid
          fi
          lsof -ti:8080 | xargs kill -9 || true
